# Generated by Django 3.2.7 on 2021-10-05 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='actor',
            field=models.CharField(default='None', max_length=250, verbose_name='Actor'),
        ),
        migrations.AddField(
            model_name='film',
            name='category',
            field=models.IntegerField(choices=[(0, 'UNCATEGORIZED'), (1, 'Hard BLOCKBUSTER')], default=0, verbose_name='Category'),
        ),
        migrations.AddField(
            model_name='film',
            name='country',
            field=models.IntegerField(choices=[(0, 'NOCOUNTRY'), (1, 'USA'), (3, 'RUSSIA')], default=0, verbose_name='Country'),
        ),
        migrations.AddField(
            model_name='film',
            name='description',
            field=models.TextField(default='', verbose_name='Description'),
        ),
    ]
