# Generated by Django 3.2.8 on 2021-10-05 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0002_auto_20211005_1737'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='./media', verbose_name='Poster'),
        ),
        migrations.AlterField(
            model_name='film',
            name='country',
            field=models.IntegerField(choices=[(0, 'NOCOUNTRY'), (1, 'USA'), (2, 'RUSSIA')], default=0, verbose_name='Country'),
        ),
    ]
