# Generated by Django 3.2.8 on 2021-10-12 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0006_alter_film_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='category',
            field=models.IntegerField(choices=[(0, 'BOEVICK'), (1, 'VESTERN'), (2, 'ARMY'), (3, 'DETEKTIV'), (4, 'KOMEDI'), (5, 'KRIMINAL'), (6, 'MELODRAMMA'), (7, 'FANTASY'), (8, 'SPORT')], default=0, verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='film',
            name='country',
            field=models.IntegerField(choices=[(0, 'NOCOUNTRY'), (1, 'USA'), (2, 'RUSSIA'), (3, 'BRITTAN')], default=0, verbose_name='Country'),
        ),
    ]
