# Generated by Django 3.2.8 on 2021-10-23 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0007_auto_20211012_1919'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='film_id',
            field=models.IntegerField(default=0, verbose_name='Film id'),
        ),
        migrations.AlterField(
            model_name='film',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='Poster'),
        ),
    ]
